### ISSUE TITLE
[Bug]: Shift-Instant Craft Crash

### ISSUE THREAD

**Issue by roshavagarga** [mrshmllow/BetterRecipeBook#101]
### What happened?

Tried to instant craft a cake, worked, when I attempted to shift-craft all possible cakes, the game crashed

### Modloader

Fabric (Default)

### Minecraft Version

1.20.2

### Mod Version

[Fabric] 1.10.0-rc2+1.20.2

### Relevant log output

```shell
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:955) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[fabric-loader-0.14.24-1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
Caused by: java.lang.ArithmeticException: / by zero
	at net.minecraft.class_514.method_48579(class_514.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25394(class_339.java:73) ~[client-intermediary.jar:?]
	at net.minecraft.class_513.method_2634(class_513.java:126) ~[client-intermediary.jar:?]
	at net.minecraft.class_507.method_25394(class_507.java:304) ~[client-intermediary.jar:?]
	at net.minecraft.class_479.method_25394(class_479.java:59) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:946) ~[client-intermediary.jar:?]
	... 6 more
```

**Comment by NiaSwift** [comment]
i have the same issue, also: it also happens when you insta-craft one, not just when you shift instacraft

**Comment by mrshmllow** [comment]
Will begin working on fixes and new releases next week.

**Comment by TauCubed** [comment]
This should be fixed as a side effect of https://github.com/mrshmllow/BetterRecipeBook/pull/106
