### ISSUE TITLE
[Bug]: Crashes when trying to un-pin a Grouped recipe

### ISSUE THREAD

**Issue by robosoup2** [mrshmllow/BetterRecipeBook#105]
### What happened?

if you pin a recipe like "powdered concrete", then the pinned recipe keeps cycling through its different color variants, and if you try to unpin the recipe it appears to do nothing (is actually pinning each color variant that it's currently on)

to fix this i try opening the group and unpinning the sub-recipes (sorry idk the technical terms) but this will always cause a crash.

[Video](https://streamable.com/en2txz)

### Modloader

Fabric (Default)

### Minecraft Version

1.20.1

### Mod Version

1.8.2

### Relevant log output

```shell
[29Nov2023 10:38:52.298] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, {MINECRAFT_USERNAME}, --version, 1.20.1, --gameDir, C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\single mod testing, --assetsDir, C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\assets, --assetIndex, 5, --uuid, {MINECRAFT_UUID}, --accessToken, ????????, --clientId, c4502edb-87c6-40cb-b595-64a280cf8906, --xuid, 0, --userType, msa, --versionType, release, --width, 854, --height, 480, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.4, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[29Nov2023 10:38:52.313] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.9 by Azul Systems, Inc.; OS Windows 11 arch amd64 version 10.0
[29Nov2023 10:38:52.503] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[29Nov2023 10:38:52.632] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[29Nov2023 10:38:52.735] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[29Nov2023 10:38:52.830] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23123!/ Service=ModLauncher Env=CLIENT
[29Nov2023 10:38:52.867] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.40, NVIDIA Corporation
[29Nov2023 10:38:53.048] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\libraries\net\minecraftforge\fmlcore\1.20.1-47.2.4\fmlcore-1.20.1-47.2.4.jar is missing mods.toml file
[29Nov2023 10:38:53.048] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.2.4\javafmllanguage-1.20.1-47.2.4.jar is missing mods.toml file
[29Nov2023 10:38:53.063] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.2.4\lowcodelanguage-1.20.1-47.2.4.jar is missing mods.toml file
[29Nov2023 10:38:53.063] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\libraries\net\minecraftforge\mclanguage\1.20.1-47.2.4\mclanguage-1.20.1-47.2.4.jar is missing mods.toml file
[29Nov2023 10:38:53.110] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[29Nov2023 10:38:54.485] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\single mod testing, --assetsDir, C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\assets, --uuid, {MINECRAFT_UUID}, --username, {MINECRAFT_USERNAME}, --assetIndex, 5, --accessToken, ????????, --clientId, c4502edb-87c6-40cb-b595-64a280cf8906, --xuid, 0, --userType, msa, --versionType, release, --width, 854, --height, 480]
[29Nov2023 10:38:59.219] [Datafixer Bootstrap/INFO] [com.mojang.datafixers.DataFixerBuilder/]: 188 Datafixer optimizations took 147 milliseconds
[29Nov2023 10:39:00.781] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23164!/assets/.mcassetsroot' uses unexpected schema
[29Nov2023 10:39:00.781] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23164!/data/.mcassetsroot' uses unexpected schema
[29Nov2023 10:39:00.809] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[29Nov2023 10:39:01.106] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: {MINECRAFT_USERNAME}
[29Nov2023 10:39:01.174] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.3.1 build 7
[29Nov2023 10:39:01.326] [modloading-worker-0/INFO] [brb/]: Loading Potions...
[29Nov2023 10:39:01.368] [modloading-worker-0/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 47.2.4, for MC 1.20.1 with MCP 20230612.114412
[29Nov2023 10:39:01.370] [modloading-worker-0/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v47.2.4 Initialized
[29Nov2023 10:39:01.728] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering S2C receiver with id architectury:sync_ids
[29Nov2023 10:39:01.731] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id architectury:sync_ids
[29Nov2023 10:39:02.616] [Render thread/INFO] [net.minecraft.server.packs.resources.ReloadableResourceManager/]: Reloading ResourceManager: vanilla, mod_resources
[29Nov2023 10:39:02.748] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forgeconfigscreens] Starting version check at https://raw.githubusercontent.com/Fuzss/modresources/main/update/forgeconfigscreens.json
[29Nov2023 10:39:02.850] [Worker-Main-10/INFO] [net.minecraft.client.gui.font.providers.UnihexProvider/]: Found unifont_all_no_pua-15.0.06.hex, loading
[29Nov2023 10:39:03.250] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forgeconfigscreens] Found status: UP_TO_DATE Current: 8.0.2 Target: null
[29Nov2023 10:39:03.250] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[29Nov2023 10:39:03.402] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: OUTDATED Current: 47.2.4 Target: 47.2.14
[29Nov2023 10:39:04.945] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/]: Missing sound for event: minecraft:item.goat_horn.play
[29Nov2023 10:39:04.946] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[29Nov2023 10:39:05.006] [Render thread/INFO] [com.mojang.blaze3d.audio.Library/]: OpenAL initialized on device OpenAL Soft on Headphone (Realtek(R) Audio)
[29Nov2023 10:39:05.008] [Render thread/INFO] [net.minecraft.client.sounds.SoundEngine/SOUNDS]: Sound engine started
[29Nov2023 10:39:05.111] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[29Nov2023 10:39:05.121] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[29Nov2023 10:39:05.122] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[29Nov2023 10:39:05.122] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[29Nov2023 10:39:05.123] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[29Nov2023 10:39:05.130] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[29Nov2023 10:39:05.136] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[29Nov2023 10:39:05.137] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[29Nov2023 10:39:05.137] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[29Nov2023 10:39:05.462] [Render thread/WARN] [net.minecraft.client.renderer.ShaderInstance/]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[29Nov2023 10:39:05.510] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[29Nov2023 10:39:05.512] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[29Nov2023 10:39:05.512] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[29Nov2023 10:39:11.951] [Render thread/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Loaded 7 recipes
[29Nov2023 10:39:12.094] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 1271 advancements
[29Nov2023 10:39:12.383] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Starting integrated minecraft server version 1.20.1
[29Nov2023 10:39:12.383] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Generating keypair
[29Nov2023 10:39:13.228] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Preparing start region for dimension minecraft:overworld
[29Nov2023 10:39:15.524] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[29Nov2023 10:39:15.524] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[29Nov2023 10:39:15.524] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[29Nov2023 10:39:15.524] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[29Nov2023 10:39:15.525] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[29Nov2023 10:39:15.752] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 6%
[29Nov2023 10:39:16.146] [Server thread/INFO] [net.minecraftforge.server.permission.PermissionAPI/]: Successfully initialized permission handler forge:default_handler
[29Nov2023 10:39:16.160] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Time elapsed: 2921 ms
[29Nov2023 10:39:16.281] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Changing view distance to 12, from 10
[29Nov2023 10:39:16.284] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Changing simulation distance to 12, from 0
[29Nov2023 10:39:16.404] [Render thread/WARN] [io.netty.util.internal.SystemPropertyUtil/]: Unable to parse the boolean system property 'java.net.preferIPv6Addresses':system - using the default value: false
[29Nov2023 10:39:17.416] [Netty Local Client IO #0/INFO] [net.minecraftforge.network.NetworkHooks/]: Connected to a modded server.
[29Nov2023 10:39:17.517] [Server thread/INFO] [net.minecraft.server.players.PlayerList/]: {MINECRAFT_USERNAME}[local:E:99f51141] logged in with entity id 153 at (-197.20393027380837, 72.0, -121.56679652958091)
[29Nov2023 10:39:17.588] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: {MINECRAFT_USERNAME} joined the game
[29Nov2023 10:39:18.195] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 27 advancements
[29Nov2023 10:39:26.307] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[29Nov2023 10:39:26.307] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[29Nov2023 10:39:26.320] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[29Nov2023 10:39:26.713] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[idealseed]'/minecraft:overworld
[29Nov2023 10:39:27.125] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[idealseed]'/minecraft:the_end
[29Nov2023 10:39:27.125] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[idealseed]'/minecraft:the_nether
[29Nov2023 10:39:27.140] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (idealseed): All chunks are saved
[29Nov2023 10:39:27.140] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[29Nov2023 10:39:27.140] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[29Nov2023 10:39:27.140] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[29Nov2023 10:39:27.501] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: keyPressed event handler
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:444) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:373) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:466) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:465) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23154!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar%23154!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1173) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-1.20.1-47.2.4.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.4.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.4.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.IllegalAccessError: failed to access class net.minecraft.client.gui.screens.recipebook.OverlayRecipeComponent$OverlayRecipeButton from class net.minecraft.client.gui.screens.inventory.AbstractContainerScreen (net.minecraft.client.gui.screens.recipebook.OverlayRecipeComponent$OverlayRecipeButton and net.minecraft.client.gui.screens.inventory.AbstractContainerScreen are in module minecraft@1.20.1 of loader 'TRANSFORMER' @44d64d4e)
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.handler$zzm000$onKeyPressed(AbstractContainerScreen.java:715) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_7933_(AbstractContainerScreen.java) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$keyPress$5(KeyboardHandler.java:383) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	... 26 more
[29Nov2023 10:39:27.522] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 8658f267-4969-4967-97d3-16f5b80864cc
[29Nov2023 10:39:27.524] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 5f7c367b-f33b-4d28-ad41-7416094071ee
```

**Comment by mrshmllow** [comment]
Reopen if this still occurs on the latest mod version for your minecraft version: https://modrinth.com/mod/brb/version/1.10.0-rc2+1.20.0-1
