### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by sternschnaube** [mrshmllow/BetterRecipeBook#112]
### What happened?

Jumped down, 6 to 8 blocks, got damage and Minecraft crashed.

### Modloader

Fabric (Default)

### Minecraft Version

1.20.2

### Mod Version

brb-1.10.0+1.20.2

### Relevant log output

```shell
java.lang.ArithmeticException: / by zero
	at net.minecraft.class_513.handler$zpn000$brb$render(class_513.java:2056)
	at net.minecraft.class_513.method_2634(class_513.java)
	at net.minecraft.class_507.method_25394(class_507.java:304)
	at net.minecraft.class_490.method_25394(class_490.java:84)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by mrshmllow** [comment]
that sounds insane and impossibly to debug probably packets from the server unlocking or something @TauCubed any ideas

**Comment by sternschnaube** [comment]
I think it's now the second time that I encounter this bug. Or maybe even the third time.

It comes from the rare side and the priority can be set really low - but I wanted to report 😊

**Comment by TauCubed** [comment]
> that sounds insane and impossibly to debug probably packets from the server unlocking recipes or something @TauCubed any ideas

It was caused by scrolling with an empty recipe book page.

**Comment by TauCubed** [comment]
I noticed that you are using version 1.20.2 (I misread it as 1.20.4) could you please test that this crash happens in that version when the following conditions are met?

- You have scrolling enabled
- You have "Showing Craftable" enabled
- You have no craftable recipes shown
- Scroll up or down while hovering the recipe book page

Thank you.

**Comment by sternschnaube** [comment]
I have to thank you, tested it right now and Minecraft instantly crashed. Good that I know now, what to avoid 😂

**Comment by sternschnaube** [comment]
Thanks for the fast fix - do you plan to publish this version soon?
