### ISSUE TITLE
[Bug]: Crash when loading a recipe into Tom's Simple Storage's Crafting Terminal

### ISSUE THREAD

**Issue by Pepsied-5229** [mrshmllow/BetterRecipeBook#133]
### What happened?

In a crafting terminal from [Tom's Simple Storage Mod](https://www.curseforge.com/minecraft/mc-mods/toms-storage) (v1.6.11 & v1.6.12), I tried clicking on an iron sword in the recipe book to load the recipe to the crafting palate, however, Minecraft then froze. Here is some of the error messages I found that may be of use. I have over 300 mods installed btw, so you may get irrelevant errors or find that another mod is to blame.

I was using BRB v1.10.0-rc3 for the log files provided, I've tested with v1.10.0-rc4 with no changes in error messages.
I also tested with a newer version of Tom's Simple Storage Mod, with no changes.

The crafting terminal's ingredients are persistent and don't drop items when you exit the screen. And when I restarted Minecraft and loaded the world back up, the ingredients to the iron sword are in the crafting terminal, which means that BRB does move the items correctly. But something afterwards crashes.
Here is the crash log. Please let me know if you need anything else, because I really love this mod.
[crash-2024-03-26_11.15.44-client.txt](https://github.com/mrshmllow/BetterRecipeBook/files/14760808/crash-2024-03-26_11.15.44-client.txt)
I really hope this gets fixed.

### Modloader

Fabric (Default)

### Minecraft Version

1.20.4

### Mod Version

1.10.0-rc3  &  1.10.0-rc4

### Relevant log output

```shell
[11:07:44] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:940) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
	at java.util.ArrayList.<init>(ArrayList.java:181) ~[?:?]
	at net.minecraft.class_514.handler$zip000$brb$getOrderedRecipes(class_514.java:530) ~[client-intermediary.jar:?]
	at net.minecraft.class_514.method_2639(class_514.java:120) ~[client-intermediary.jar:?]
	at net.minecraft.class_514.method_48579(class_514.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25394(class_339.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_513.method_2634(class_513.java:126) ~[client-intermediary.jar:?]
	at net.minecraft.class_507.method_25394(class_507.java:304) ~[client-intermediary.jar:?]
	at com.tom.storagemod.gui.CraftingTerminalScreen.method_25394(CraftingTerminalScreen.java:129) ~[toms_storage_fabric-1.20.4-1.6.11.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.redirect$eml000$jsmacros$onRender(class_757.java:9621) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.mixinextras$bridge$redirect$eml000$jsmacros$onRender$258(class_757.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.wrapOperation$djp000$fabric-screen-api-v1$onRenderScreen(class_757.java:6111) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:931) ~[client-intermediary.jar:?]
	... 9 more
[11:07:44] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[11:07:44] [Render thread/INFO]: [STDERR]: java.lang.Throwable
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1008.handler$eeh000$immersive_portals$onLogging(class_1008.java:522)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1008.method_4224(class_1008.java:104)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GL11C.glPolygonMode(Native Method)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GL11.glPolygonMode(GL11.java:4987)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.platform.GlStateManager._polygonMode(GlStateManager.java:470)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.polygonMode(RenderSystem.java:407)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.utils.GlUtil.resetState(GlUtil.java:39)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.resetStates(InGameCatcher.java:42)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:33)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.modify$fhi000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:29838)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:908)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:265)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
[11:07:44] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[11:07:44] [Render thread/INFO]: [STDERR]: java.lang.Throwable
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1008.handler$eeh000$immersive_portals$onLogging(class_1008.java:522)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1008.method_4224(class_1008.java:104)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GL11C.glPolygonMode(Native Method)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GL11.glPolygonMode(GL11.java:4987)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.platform.GlStateManager._polygonMode(GlStateManager.java:470)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.polygonMode(RenderSystem.java:407)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.utils.GlUtil.resetState(GlUtil.java:40)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.resetStates(InGameCatcher.java:42)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:33)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.modify$fhi000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:29838)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:908)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:265)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
[11:07:44] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)




[11:15:44] [Render thread/FATAL]: Minecraft ran into a problem! Report saved to: E:\PrismLauncher\instances\1.20.4 QoL 2.0\.minecraft\crash-reports\crash-2024-03-26_11.15.44-client.txt
---- Minecraft Crash Report ----
// My bad.

Time: 2024-03-26 11:15:44
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at net.minecraft.class_514.handler$zip000$brb$getOrderedRecipes(class_514.java:530)
	at net.minecraft.class_514.method_2639(class_514.java:120)
	at net.minecraft.class_514.method_48579(class_514.java:98)
	at net.minecraft.class_339.method_25394(class_339.java:66)
	at net.minecraft.class_513.method_2634(class_513.java:126)
	at net.minecraft.class_507.method_25394(class_507.java:304)
	at com.tom.storagemod.gui.CraftingTerminalScreen.method_25394(CraftingTerminalScreen.java:129)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.redirect$eml000$jsmacros$onRender(class_757.java:9621)
	at net.minecraft.class_757.mixinextras$bridge$redirect$eml000$jsmacros$onRender$258(class_757.java)
	at net.minecraft.class_757.wrapOperation$djp000$fabric-screen-api-v1$onRenderScreen(class_757.java:6111)
	at net.minecraft.class_757.method_3192(class_757.java:931)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at net.minecraft.class_514.handler$zip000$brb$getOrderedRecipes(class_514.java:530)
	at net.minecraft.class_514.method_2639(class_514.java:120)
	at net.minecraft.class_514.method_48579(class_514.java:98)
	at net.minecraft.class_339.method_25394(class_339.java:66)
	at net.minecraft.class_513.method_2634(class_513.java:126)
	at net.minecraft.class_507.method_25394(class_507.java:304)
	at com.tom.storagemod.gui.CraftingTerminalScreen.method_25394(CraftingTerminalScreen.java:129)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.redirect$eml000$jsmacros$onRender(class_757.java:9621)
	at net.minecraft.class_757.mixinextras$bridge$redirect$eml000$jsmacros$onRender$258(class_757.java)
	at net.minecraft.class_757.wrapOperation$djp000$fabric-screen-api-v1$onRenderScreen(class_757.java:6111)

-- Screen render details --
Details:
	Screen name: com.tom.storagemod.gui.CraftingTerminalScreen
	Mouse location: Scaled: (420, 221). Absolute: (841.000000, 442.000000)
	Screen size: Scaled: (960, 514). Absolute: (1920, 1027). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:931)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)





[11:15:44] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: null
	at net.pcal.fastback.mod.fabric.FabricClientProvider.setMinecraftClient(FabricClientProvider.java:58) ~[fastback-0.17.0+1.20.4-fabric.jar:?]
	at net.pcal.fastback.mod.fabric.FabricClientInitializer.lambda$onInitializeClient$0(FabricClientInitializer.java:49) ~[fastback-0.17.0+1.20.4-fabric.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.3.0+a67ffb5d4f-7b08e9468e9a8df7.jar:?]
	at net.minecraft.class_310.handler$ddk000$fabric-lifecycle-events-v1$onStart(class_310.java:18288) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:870) ~[client-intermediary.jar:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:38) ~[notenoughcrashes-4.4.7+1.20.4-fabric.jar:?]
	at net.minecraft.class_310.modify$fhi000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:29838) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:908) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[11:15:44] [CullThread/INFO]: [STDOUT]: Shutting down culling task!
[11:15:44] [Render thread/INFO]: Stopping!
[11:15:44] [Render thread/INFO]: [EMI] Disconnecting from server, EMI data cleared
[11:15:44] [Thread-52/INFO]: [EMI] Clearing data
[11:15:44] [Render thread/INFO]: Shutting down renderer (fabric)
[11:15:44] [Render thread/INFO]: Renderer shutting down.
Process exited with code 0.
```

**Comment by mrshmllow** [comment]
> I have over 300 mods installed btw, so you may get irrelevant errors or find that another mod is to blame.

For the future please bisect your mods before making an issue
Ill let it pass for now
