### ISSUE TITLE
Error when loading brb in forge 1.18.2 40.1.54

### ISSUE THREAD

**Issue by Shraggy-byte** [mrshmllow/BetterRecipeBook#50]
This is the Error Message, all dependencies are installed.

Thank you for your time and your wonderful plugin!

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/4/22, 2:50 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.1.54-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.18.2-40.1.54-universal.jar%2396!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.1.54.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.1.54.jar%2316!/:1.0] {}
-- MOD brb --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.54.jar%2393!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.54.jar%2392!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: brb-1.18.2-forge-1.5.6.jar
	Failure message: Better Recipe Book (brb) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.5.6
	Mod Issue URL: https://github.com/mrshmllow/BetterRecipeBook/issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.1.54.jar%2316!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at marsh.town.brb.BetterRecipeBook.init(BetterRecipeBook.java:37) ~[brb-1.18.2-forge-1.5.6.jar%2345!/:?] {re:classloading,re:mixin}
	at marsh.town.brb.forge.BetterRecipeBookForge.<init>(BetterRecipeBookForge.java:9) ~[brb-1.18.2-forge-1.5.6.jar%2345!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.54.jar%2393!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.54.jar%2392!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.4.151-1-pve
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2687286848 bytes (2562 MiB) / 3061841920 bytes (2920 MiB) up to 3061841920 bytes (2920 MiB)
	CPUs: 80
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
	Identifier: Intel64 Family 6 Model 79 Stepping 1
	Microarchitecture: Broadwell (Server)
	Frequency (GHz): 2.20
	Number of physical packages: 2
	Number of physical CPUs: 40
	Number of logical CPUs: 80
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 288455.47
	Virtual memory used (MB): 429728.44
	Swap memory total (MB): 30517.00
	Swap memory used (MB): 1784.59
	JVM Flags: 4 total; -Xms750M -Xmx2919M -Xss512k -XX:ParallelGCThreads=1
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		YungsBetterDungeons-1.18.2-Forge-2.1.0.jar        |YUNG's Better Dungeons        |betterdungeons                |1.18.2-Forge-2.1.0  |COMMON_SET|Manifest: NOSIGNATURE
		netherportalfix-forge-1.18-9.0.0.jar              |NetherPortalFix               |netherportalfix               |9.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		DoggyTalents-1.18.2-2.5.0.jar                     |Doggy Talents 2               |doggytalents                  |2.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.18.2-8.0.0+10.jar                  |Clumps                        |clumps                        |8.0.0+10            |COMMON_SET|Manifest: NOSIGNATURE
		XaerosWorldMap_1.24.0_Forge_1.18.2.jar            |Xaero's World Map             |xaeroworldmap                 |1.24.0              |COMMON_SET|Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.18.2-12.0.2.jar      |CookingForBlockheads          |cookingforblockheads          |12.0.2              |COMMON_SET|Manifest: NOSIGNATURE
		Placebo-1.18.2-6.4.1.jar                          |Placebo                       |placebo                       |6.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		artifacts-1.18.2-4.1.0.jar                        |Artifacts                     |artifacts                     |1.18.2-4.1.0        |COMMON_SET|Manifest: NOSIGNATURE
		SereneSeasons-1.18.2-7.0.0.15.jar                 |Serene Seasons                |sereneseasons                 |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		configured-1.5.3-1.18.2.jar                       |Configured                    |configured                    |1.5.3               |COMMON_SET|Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-2.0.8.jar                   |YUNG's API                    |yungsapi                      |1.18.2-Forge-2.0.8  |COMMON_SET|Manifest: NOSIGNATURE
		Decorative Blocks-forge-1.18.2-2.1.0.jar          |Decorative Blocks             |decorative_blocks             |2.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		betteranimalsplus-1.18.2-11.0.5-forge.jar         |Better Animals Plus           |betteranimalsplus             |1.18.2-11.0.5       |COMMON_SET|Manifest: NOSIGNATURE
		bonsaitrees3-3.1.0.jar                            |Bonsai Trees 3                |bonsaitrees3                  |3.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		balm-3.1.0+0.jar                                  |Balm                          |balm                          |3.1.0+0             |COMMON_SET|Manifest: NOSIGNATURE
		carryon-1.18.2-1.17.0.8.jar                       |Carry On                      |carryon                       |1.17.0.8            |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-6.2.62-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.2.62              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.1.54-universal.jar                |Forge                         |forge                         |40.1.54             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		mob_grinding_utils-1.18.2-0.4.39.jar              |Mob Grinding Utils            |mob_grinding_utils            |1.18.2-0.4.39       |COMMON_SET|Manifest: NOSIGNATURE
		refinedstorage-1.10.2.jar                         |Refined Storage               |refinedstorage                |1.10.2              |COMMON_SET|Manifest: NOSIGNATURE
		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |COMMON_SET|Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.4.6.jar                  |Supplementaries               |supplementaries               |1.18.2-1.4.6        |COMMON_SET|Manifest: NOSIGNATURE
		ironchest-1.18.2-13.1.9.jar                       |Iron Chests                   |ironchest                     |1.18.2-13.1.9       |COMMON_SET|Manifest: NOSIGNATURE
		server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: NOSIGNATURE
		TConstruct-1.18.2-3.5.1.31.jar                    |Tinkers' Construct            |tconstruct                    |3.5.1.31            |COMMON_SET|Manifest: NOSIGNATURE
		industrial-foregoing-1.18.2-3.3.1.4-8.jar         |Industrial Foregoing          |industrialforegoing           |3.3.1.4             |COMMON_SET|Manifest: NOSIGNATURE
		FarmersDelight-1.18.2-1.1.2.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.1.2        |COMMON_SET|Manifest: NOSIGNATURE
		theoneprobe-1.18-5.1.0.jar                        |The One Probe                 |theoneprobe                   |1.18-5.1.0          |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.1.0.102.jar           |TerraBlender                  |terrablender                  |1.18.2-1.1.0.102    |COMMON_SET|Manifest: NOSIGNATURE
		titanium-1.18.2-3.5.6-38.jar                      |Titanium                      |titanium                      |3.5.6               |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.134.jar               |Biomes O' Plenty              |biomesoplenty                 |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		NethersDelight-1.18.2-2.2.0.jar                   |Nethers Delight               |nethersdelight                |2.2                 |COMMON_SET|Manifest: NOSIGNATURE
		betterfpsdist-1.18.2-1.5.jar                      |betterfpsdist mod             |betterfpsdist                 |1.18.2-1.5          |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |COMMON_SET|Manifest: NOSIGNATURE
		Mantle-1.18.2-1.9.27.jar                          |Mantle                        |mantle                        |1.9.27              |COMMON_SET|Manifest: NOSIGNATURE
		gravestone-1.18.2-1.0.2.jar                       |Gravestone Mod                |gravestone                    |1.18.2-1.0.2        |COMMON_SET|Manifest: NOSIGNATURE
		StorageDrawers-1.18.2-10.2.1.jar                  |Storage Drawers               |storagedrawers                |10.2.1              |COMMON_SET|Manifest: NOSIGNATURE
		libnonymous-2.1.0.jar                             |libnonymous                   |libnonymous                   |2.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		soultrap-1.18.2-1.0.0.jar                         |Soul Trap                     |soultrap                      |1.18.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		cfm-7.0.0-pre29-1.18.2.jar                        |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre29         |COMMON_SET|Manifest: NOSIGNATURE
		architectury-4.5.75-forge.jar                     |Architectury                  |architectury                  |4.5.75              |COMMON_SET|Manifest: NOSIGNATURE
		brb-1.18.2-forge-1.5.6.jar                        |Better Recipe Book            |brb                           |1.5.6               |ERROR     |Manifest: NOSIGNATURE
		ferritecore-4.2.1-forge.jar                       |Ferrite Core                  |ferritecore                   |0.0NONE             |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		refinedstorageaddons-0.8.2.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.8.2               |COMMON_SET|Manifest: NOSIGNATURE
		FastLeafDecay-28.jar                              |FastLeafDecay                 |fastleafdecay                 |28                  |COMMON_SET|Manifest: NOSIGNATURE
		expandability-6.0.0.jar                           |ExpandAbility                 |expandability                 |6.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		CodeChickenLib-1.18.2-4.1.1.462-universal.jar     |CodeChicken Lib               |codechickenlib                |4.1.1.462           |COMMON_SET|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		EnderStorage-1.18.2-2.9.0.177-universal.jar       |EnderStorage                  |enderstorage                  |2.9.0.177           |COMMON_SET|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		YungsBetterMineshafts-1.18.2-Forge-2.1.4.jar      |YUNG's Better Mineshafts      |bettermineshafts              |1.18.2-Forge-2.1.4  |COMMON_SET|Manifest: NOSIGNATURE
		valhelsia_core-1.18.2-0.3.1.jar                   |Valhelsia Core                |valhelsia_core                |1.18.2-0.3.1        |COMMON_SET|Manifest: NOSIGNATURE
		valhelsia_structures-forge-1.18.2-0.1.0.jar       |Valhelsia Structures          |valhelsia_structures          |1.18.2-0.1.0        |COMMON_SET|Manifest: NOSIGNATURE
		mcw-lights-1.0.3-mc1.18.2.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 26728223-73e8-4629-a91b-059d1c6dd610
	FML: 40.1
	Forge: net.minecraftforge:40.1.54

**Comment by mrshmllow** [comment]
Hello! No idea, you have a load of mods. 1.18 is not supported anymore, and it works for me
