### ISSUE TITLE
crash in 1.19.3

### ISSUE THREAD

**Issue by JosefLitos** [mrshmllow/BetterRecipeBook#57]
```log
Description: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'brb'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.NoSuchFieldError: field_11143
	at marsh.town.brb.BrewingStand.Result.<init>(Result.java:23)
	at marsh.town.brb.Loaders.PotionLoader.init(PotionLoader.java:28)
	at marsh.town.brb.BetterRecipeBook.init(BetterRecipeBook.java:28)
	at marsh.town.brb.fabric.BetterRecipeBookFabric.onInitialize(BetterRecipeBookFabric.java:9)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 17 more
```

**Comment by PweSol** [comment]
can confirm, crashes on 1.19.3

**Comment by mrshmllow** [comment]
every update I essentially have to rewrite the entire mod, since it mixins so much. I tried to get 1.19 to work but I gave up since the task was so daunting

**Comment by Kichura** [comment]
It's best to take your time instead of having to dedicate yourself into mods heavily as it can cause burn out when updating alot.

**Comment by sternschnaube** [comment]
Hello @mrshmllow, would love to see the mod for 1.19.3 as well 😊
It's really frustrating how Mojang wants to go the way now, with less or more bigger changes between minor versions...

**Comment by Aces-and-Jacks** [comment]
Since there's a 1.19.3 version wouldn't it make sense to close this issue?

**Comment by sternschnaube** [comment]
Thanks for the notify @Aces-and-Jacks.
Pleae upload the newest release on Modrinth @mrshmllow 😊

**Comment by mrshmllow** [comment]
I couldn't, it was bugged out

**Comment by mrshmllow** [comment]
@sternschnaube fixed

**Comment by sternschnaube** [comment]
Thanks 😇

**Comment by mrshmllow** [comment]
I don't mind! feel free to upstream anything or whatever but it's cool

**Comment by Aces-and-Jacks** [comment]
> fixed

Earlier I think I saw the different versions being there. Tho unless I'm wrong and it was all meant to be in one file which doesn't seem correct, I think it broke again

**Comment by sternschnaube** [comment]
Works flawless on 1.19.3 for me.
I got the file from Curse.

**Comment by Aces-and-Jacks** [comment]
Oh, yeah 1.19.3 on curseforge works great. Just on modrinth it's broken I think

**Comment by JosefLitos** [comment]
I just used my launcher to find and select the mod from Modrinth and it listed only one available version for 1.19.3 - 1.7.0.

**Comment by mrshmllow** [comment]
modrinth versions had their files replaced with the curseforge equivalent

**Comment by Aces-and-Jacks** [comment]
Ok I feel like an idiot now. I've been looking at the wrong link without realizing it. Sorry for the trouble
