### ISSUE TITLE
crash in 1.19.4

### ISSUE THREAD

**Issue by MehradN** [mrshmllow/BetterRecipeBook#64]
Sorry to inform you, but it seems like the mod crashes on 1.19.4.
```
[20:30:53] [Render thread/ERROR]: Mixin apply for mod brb failed mixins.brb-common.json:RemoveBookButton from mod brb -> net.minecraft.class_344: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on renderButton could not find any targets matching 'Lnet/minecraft/class_344;method_25359(Lnet/minecraft/class_4587;IIF)V' in net.minecraft.class_344. Using refmap brb-common-refmap.json [PREINJECT Applicator Phase -> mixins.brb-common.json:RemoveBookButton from mod brb -> Prepare Injections ->  -> handler$zdh001$brb$renderButton(Lnet/minecraft/class_4587;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on renderButton could not find any targets matching 'Lnet/minecraft/class_344;method_25359(Lnet/minecraft/class_4587;IIF)V' in net.minecraft.class_344. Using refmap brb-common-refmap.json [PREINJECT Applicator Phase -> mixins.brb-common.json:RemoveBookButton from mod brb -> Prepare Injections ->  -> handler$zdh001$brb$renderButton(Lnet/minecraft/class_4587;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at jdk.internal.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.17.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_442.method_25426(class_442.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:427) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1079) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:681) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:198) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.17.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

Full log can be found [here](https://pastebin.com/f4dCXasD).

**Comment by MehradN** [comment]
I tried to help and fix the problem myself, but I'm don't have enough knowledge for it. But here are the things I found out.
Sorry, I didn't know how to deal with `RegistryAccess`, so I couldn't progress any longer. Also there was an error about `dev.architectury.mixin.fabric.MixinFarmBlock`, I didn't know how to deal with that also.

In the following locations, you need to rename `renderButton` to `renderWidget`:
- [AlternativeRecipes:34](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/Mixins/AlternativeRecipes.java#L34)
- [AlternativeRecipes:41](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/Mixins/AlternativeRecipes.java#L41)
- [AlternativeRecipes:42](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/Mixins/AlternativeRecipes.java#L42)
- [AnimatedResultButton:47](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/BrewingStand/AnimatedResultButton.java#L47)
- [RemoveBookButton:26](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/Mixins/RemoveBookButton.java#L26)
- [RemoveBookButton:27](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/Mixins/RemoveBookButton.java#L27)

In the following location, you need to rename `render` to `renderWidget`:
- [RecipeBookWidget:322](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/BrewingStand/RecipeBookWidget.java#L322)

In the following location, you need to rename `setFocus` to `setFocused`:
- [RecipeBookWidget:470](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/BrewingStand/RecipeBookWidget.java#L470)

In the following locations, you need to pass `matrices` as the first argument: (It doesn't replace any other arguments)
- [AlternativeRecipes:62](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/Mixins/AlternativeRecipes.java#L62)
- [AlternativeRecipes:80](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/Mixins/AlternativeRecipes.java#L80)
- [AnimatedResultButton:78](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/BrewingStand/AnimatedResultButton.java#L78)
- [AnimatedResultButton:79](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/BrewingStand/AnimatedResultButton.java#L79)
- [RecipeBookGhostSlots:54](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/BrewingStand/RecipeBookGhostSlots.java#L54)
- [RecipeBookGhostSlots:59](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/BrewingStand/RecipeBookGhostSlots.java#L59)
- [RecipeGroupButtonWidget:48](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/BrewingStand/RecipeGroupButtonWidget.java#L48)
- [RecipeGroupButtonWidget:51](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/BrewingStand/RecipeGroupButtonWidget.java#L51)
- [RecipeGroupButtonWidget:55](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/BrewingStand/RecipeGroupButtonWidget.java#L55)
- [RecipeGroupButtonWidget:57](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/BrewingStand/RecipeGroupButtonWidget.java#L57)
- [RecipeGroupButtonWidget:58](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/BrewingStand/RecipeGroupButtonWidget.java#L58)

In the following locations, you need to pass a `RegistryAccess` as the first argument: (I don't know how)
- [AlternativeRecipes:74](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/Mixins/AlternativeRecipes.java#L74)
- [InstantCraftingManager:21](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/InstantCraftingManager.java#L21)
- [Pins:47](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/Mixins/Pins/Pins.java#L47)
- [Search:33](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/Mixins/UnGroup/Search.java#L33)
- [SplitGrouped:37](https://github.com/mrshmllow/BetterRecipeBook/blob/1.19/common/src/main/java/marsh/town/brb/Mixins/UnGroup/SplitGrouped.java#L37)

**Comment by MehradN** [comment]
#65 seem to fix the problem.

**Comment by mrshmllow** [comment]
sorry to hear that. never said it would
