### ISSUE TITLE
Game Crashes when opening Settings [ 1.19.4 Quilt ]

### ISSUE THREAD

**Issue by MrEnxo** [mrshmllow/BetterRecipeBook#66]
Error:
```
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:946) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1218) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527) ~[quilt-loader-0.18.8.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.18.8.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.18.8.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void me.shedaniel.clothconfig2.gui.ClothConfigScreen.method_25434(int)'
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.method_25394(ClothConfigScreen.java:234) ~[transformed-mod-cloth-config.i0:0/:?]
	at net.minecraft.class_437.method_47413(class_437.java:121) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_757.method_3192(class_757.java:937) ~[transformed-mod-minecraft.i0:0/:?]
	... 13 more
```
Mod List:
```
  [✔] animatica-0.5+1.19
  [✔] architectury-8.1.79-fabric
  [✔] borderless-mining-1.1.7+1.19.4
  [✔] brb-1.7.2-fabric
  [✔] c2me-fabric-mc1.19.4-0.2.0+alpha.10.42
  [✔] capes-1.5.2+1.19.3-fabric
  [✔] CITResewn-1.1.3+1.19.4
  [✔] continuity-3.0.0-beta.2+1.19.3
  [✔] entity_model_features_fabric_1.19.4-0.2.4
  [✔] entity_texture_features_fabric_1.19.4-4.3.5
  [✔] entityculling-fabric-1.6.2-mc1.19.4
  [✔] exordium-fabric-1.0.3-mc1.19.4
  [✔] fabric-language-kotlin-1.9.3+kotlin.1.8.20
  [✔] fabricskyboxes-0.6.5+mc1.19.4
  [✔] Fastload+1.19.4-2.7
  [✔] fastquit-2.1.0+1.19.3
  [✔] ferritecore-5.2.0-fabric
  [✔] fsb-interop-1.2.0+mc1.19.4-build.31
  [✔] ImmediatelyFast-1.1.11+1.19.4
  [✔] indium-1.0.15+mc1.19.4
  [✔] iris-mc1.19.4-1.5.2
  [✔] krypton-0.2.2
  [✔] lambdabettergrass-1.5.0+1.19.4
  [✔] lambdynamiclights-2.3.0+1.19.4
  [✔] lazydfu-0.1.3
  [✔] litematica-fabric-1.19.4-0.14.2
  [✔] lithium-fabric-mc1.19.4-0.11.1
  [✔] main-menu-credits-1.1.1
  [✔] malilib-fabric-1.19.4-0.15.3
  [✔] memoryleakfix-fabric-1.17+-1.0.0
  [✔] modmenu-6.1.0-rc.4
  [✔] moreculling-1.19.4-0.17.0
  [✔] MouseTweaks-fabric-mc1.19.4-2.24
  [✘] mousewheelie-1.10.7+mc1.19.3.jar (disabled)
  [✔] ok_zoomer-5.0.0-beta.11+1.19.4
  [✔] optigui-2.0.0-beta.3
  [✔] puzzle-1.5.0+1.19.4
  [✔] qfapi-6.0.0-beta.3_qsl-5.0.0-beta.2_fapi-0.76.0_mc-1.19.4
  [✔] reeses_sodium_options-1.5.0+mc1.19.4-build.72
  [✔] smoothboot-fabric-1.19.4-1.7.0
  [✔] sodium-extra-0.4.18+mc1.19.4-build.100
  [✔] sodium-fabric-mc1.19.4-0.4.10+build.24
  [✔] starlight-1.1.1+fabric.ae22326
  [✔] tweakeroo-fabric-1.19.4-0.16.0
  [✔] vmp-fabric-mc1.19.4-0.2.0+beta.7.69-all
  [✔] Xaeros_Minimap_23.3.3_Fabric_1.19.4
  [✔] XaerosWorldMap_1.29.5_Fabric_1.19.4
  [✔] YetAnotherConfigLib-2.4.0
  [✔] yosbr-0.1.1

```

**Comment by MrEnxo** [comment]
NVM GUYS IM STUPID SORrY FOR OPENING A USELESS ISSUE
didnt have cloth config api, you should probably make that a dependency or something.

**Comment by mrshmllow** [comment]
it is listed many times as a dependency you only have to read the readme for 2 nanoseconds
