### ISSUE TITLE
Crash on 1.20.2 

### ISSUE THREAD

**Issue by sternschnaube** [mrshmllow/BetterRecipeBook#92]
Fabric. While I tried to open the Smithing Table gui.

java.lang.IllegalAccessError: class marsh.town.brb.recipe.smithing.BRBSmithingTrimRecipe tried to access method 'void net.minecraft.class_8062.<init>(net.minecraft.class_1856, net.minecraft.class_1856, net.minecraft.class_1856)' (marsh.town.brb.recipe.smithing.BRBSmithingTrimRecipe and net.minecraft.class_8062 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3bbc39f8)
	at marsh.town.brb.recipe.smithing.BRBSmithingTrimRecipe.<init>(BRBSmithingTrimRecipe.java:21)
	at marsh.town.brb.recipe.smithing.BRBSmithingTrimRecipe.from(BRBSmithingTrimRecipe.java:30)
	at marsh.town.brb.smithingtable.SmithingRecipeBookComponent.getCollectionsForCategory(SmithingRecipeBookComponent.java:124)
	at marsh.town.brb.generic.GenericRecipeBookComponent.updateCollections(GenericRecipeBookComponent.java:252)
	at marsh.town.brb.generic.GenericRecipeBookComponent.initVisuals(GenericRecipeBookComponent.java:140)
	at marsh.town.brb.smithingtable.SmithingRecipeBookComponent.init(SmithingRecipeBookComponent.java:39)
	at net.minecraft.class_4895.handler$zmb004$brb$init(class_4895.java:546)
	at net.minecraft.class_4895.method_25445(class_4895.java:72)
	at net.minecraft.class_4894.method_25426(class_4894.java:26)
	at net.minecraft.class_437.method_25423(class_437.java:298)
	at net.minecraft.class_310.method_1507(class_310.java:1135)
	at net.minecraft.class_3929$class_3930.method_17543(class_3929.java:65)
	at net.minecraft.class_3929.method_17541(class_3929.java:51)
	at net.minecraft.class_634.method_17587(class_634.java:1150)
	at net.minecraft.class_3944.method_17591(class_3944.java:37)
	at net.minecraft.class_3944.method_11054(class_3944.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:23)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.mixinextras$bridge$method_18859$5(class_4093.java)
	at net.minecraft.class_4093.wrapOperation$dbi000$carpet-tis-addition$yeetUpdateSuppressionCrash_implForThreadExecutorTaskExecuting(class_4093.java:570)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1231)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by mrshmllow** [comment]
closed by https://github.com/mrshmllow/BetterRecipeBook/commit/ab4ce7836e0ce97c003933e08652b0fe2d6889f5
